n= input('Digite algo: ')
print('É uma letra? {}'.format(n.isnumeric()))
print('É uma letra? {}'.format(n.isalpha()))
print('É um decimal? {}'.format(n.isdecimal()))
print('Está capitalizado? {}'.format(n.istitle()))
print('Está em maiusculo? {}'.format(n.isupper()))
print('Está em minusculo? {}'.format(n.islower()))
print('Tem espaço? {}'.format(n.isspace()))
print('seu tipo primitivo é', type(n))