nome= str(input('Digite um nome: ')).lower().strip()
espaço=nome.split()
juntar=''.join(espaço)
letra= nome.count('a')
primeira= juntar.find('a')
ultima=juntar.rfind('a')
print(f'tem {letra} letras A')
print(f'A primeira letra A aparece na {primeira+1} posição')
print(f'A ultima letra A aparece na {ultima+1} posição')